---
- hosts: all
  vars: 
    py3env: /home/vagrant/py3env
    dbname: aurora
    dbuser: aurora_dbuser
    dbpassword: nosecret
    ansible_python_interpreter: "/usr/local/bin/python3"
  tasks:
#  - name: apt-get update
#    apt: update_cache=yes
#    sudo: yes
  - command: locale-gen en_US.UTF-8
  - command: update-locale LANG=en_US.UTF-8
  - apt: pkg=vim
  - apt: pkg=libjpeg-dev

  - apt: pkg=postgresql
  - apt: pkg=python-psycopg2
#  - apt: pkg=postgresql-server-dev-9.1
  - apt: pkg=libpq-dev

  - name: throw away postgres cluster
    command: pg_dropcluster --stop 9.3 main
    sudo: yes
    sudo_user: postgres

  - name: create new postgres cluster with UTF-8 encoding
    command: pg_createcluster --locale=en_US.UTF-8 --start 9.3 main
    sudo: yes
    sudo_user: postgres

  - postgresql_user: name={{ dbuser }}
                     password={{ dbpassword }}
    sudo: yes
    sudo_user: postgres

  - name: create database {{ dbname }}
    postgresql_db: name={{ dbname }}
                   owner={{ dbuser }}
                   encoding='UTF-8'
                   lc_collate='en_US.UTF-8'
                   lc_ctype='en_US.UTF-8'
    sudo: yes
    sudo_user: postgres

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
    sudo: yes
    sudo_user: postgres

  - apt: pkg=python-pip
  - apt: pkg=python3
  - apt: pkg=python3-dev
  - apt: pkg=rabbitmq-server
  - pip: name=virtualenv
  - name: create virtualenv
    command: virtualenv -p /usr/bin/python3 {{ py3env }}
             creates={{ py3env }}
    sudo: yes
    sudo_user: vagrant
  - name: "Copy virtualenv wrapper file"
    synchronize: src=pyvenv
                 dest="{{ py3env }}/bin/pyvenv"
  vars:
    ansible_python_interpreter: "{{ py3env }}/bin/pyvenv"
  tasks:
# ipython not working with python manage.py shell anymore :(
  - name: install ipython into virtualenv
    pip: name=ipython
         virtualenv={{ py3env }}
    sudo: yes
    sudo_user: vagrant
  - name: install psycopg2 into virtualenv
    pip: name=psycopg2
         virtualenv={{ py3env }}
    sudo: yes
    sudo_user: vagrant
  - name: install project requirements
    pip: requirements=/vagrant/requirements_dev.txt
         virtualenv={{ py3env }}
    sudo: yes
    sudo_user: vagrant

  - name: add automatic activation of virtualenv to .bashrc
    lineinfile: dest=/home/vagrant/.bashrc
                line=". {{ py3env }}/bin/activate"
    sudo: yes
    sudo_user: vagrant
  - lineinfile: dest=/home/vagrant/.bashrc
                line='cd /vagrant'
    sudo: yes
    sudo_user: vagrant
  - lineinfile: dest=/home/vagrant/.bashrc
                line='export LANGUAGE=en_US.UTF-8'
    sudo: yes
    sudo_user: vagrant
  - lineinfile: dest=/home/vagrant/.bashrc
                line='export LANG=en_US.UTF-8'
    sudo: yes
    sudo_user: vagrant
  - lineinfile: dest=/home/vagrant/.bashrc
                line='export LC_ALL=en_US.UTF-8'
    sudo: yes
    sudo_user: vagrant
  - name: Build sherlock
    shell: "cd /vagrant/PlagCheck/hashing/sherlock && python setup install"
  - name: start message queue
    command: "{{ py3env }}/bin/celery -A PlagCheck worker --concurrency=1 --loglevel=DEBUG --detach"
    sudo: no
  - name: start aurora
    command: "{{ py3env }}/bin/python manage.py runserver 0.0.0.0:8001"
    sudo: no
  - name: start message queue monitor
    sudo: no
    command: "{{ py3env }}/bin/celery -A PlagCheck flower --loglevel=DEBUG"
